### DISCUSSION TITLE
Preview 2.0.93

### DISCUSSION THREAD

**Discussion by heimanba** [Serverless-Devs/Serverless-Devs#269] [Ideas]
## bug
- #287
- #286

## 优化
-  #265
- #285
- #293

## 功能更新
- #283
-  #246
-  #229
- #273
- #289
- #291
- #313
## s 指令更新
- #274
- #275 
- #276 
- #277
- #278 
- #280

**Comment by anycodes** [comment]
在项目帮助下，丢失项目本身的帮助信息，例如，我当前项目是：

```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: fcDeployApp       #  项目名称
access: "default"  #  秘钥别名

services:
  fc-deploy-test: #  服务名称
    component: devsapp/fc  # 组件名称
    props: #  组件的属性值
      region: cn-hangzhou
      service:
        name: fc-deploy-service
        description: 'demo for fc-deploy component'
        internetAccess: true
        logConfig: auto
      function:
        name: http-trigger-py36
        description: this is a test
        runtime: python3
        codeUri: ./code
        # ossBucket:
        # ossKey:  # conflict with codeUri
        handler: index.handler
        memorySize: 128
        timeout: 60
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
                - POST
```

我执行`s -h`的时候，应该是：

```
Usage: s [options] [command]

  _________                               .__
 /   _____/ ______________  __ ___________|  |   ____   ______ ______
 \_____  \_/ __ \_  __ \  \/ // __ \_  __ \  | _/ __ \ /  ___//  ___/
 /        \  ___/|  | \/\   /\  ___/|  | \/  |_\  ___/ \___ \ \___ \
/_________/\_____>__|    \_/  \_____>__|  |____/\_____>______>______>

Welcome to the Serverless Devs.

More: 
📘 Documents: https://www.serverless-devs.com
🙌 Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions

Quick start:
🍻 Can perform [s init] fast experience

Options:
  -t, --template [templatePath]  Specify the template file.
  -a, --access [aliasName]       Specify the access alias name.
  --skip-actions                 Skip the extends section.
  --debug                        Open debug model.
  -v, --version                  Output the version number.
  -h, --help                     Display help for command.

Commands:
  config                         👤 Configure venders account.
  init                              💞 Initializing a serverless project.
  cli                               🐚 Command line operation without yaml mode.
  set                             🔧 Settings for the tool.
  clean                          💥 Clean up the environment.
  component                🔌 Installed component information.
  fc-deploy-test           👉 This is a customer command, please use [s fc-deploy-test -h]  obtain the help.
```
