### DISCUSSION TITLE
关于Yaml规范和标准的升级

### DISCUSSION THREAD

**Discussion by anycodes** [Serverless-Devs/Serverless-Devs#30] [Ideas]
目前Serverless devs的Yaml规范为：
```yaml
Global: 全局变量
ProjectName:
  Component: 组件
  Properties: 属性参数     
```

例如：
```yaml
Global: 
   Region: cn-shenzhen
DjangoProject:
  Component: django
  Properties:
    Region: cn-hongkong
    Service:
      Name: serverless-china
    Function:
      Name: test
      Src: ./
ReactProject:
  Component: react
  Properties:
    Region: cn-hongkong
    Backend: ${DjangoProject.Output.Url}
```

希望升级之后的规范为：

```yaml
Name: 整个项目的名字
Stage: 整个项目的阶段，例如dev，test，release等
Global: 全局变量
Project:
  Component: 组件
  Properties: 属性参数     
Projects:
  ProjectName:
    Component: 组件
    Properties: 属性参数    
  ProjectName:
    Component: 组件
    Properties: 属性参数    
```

这其中，`Project`和`Projects`仅可以出现一个，即要不出现`Project`，要不出现`Projects`。

例如，单个Project：

```yaml
Name: MyWebsite
Stage: dev
Global:
  Region: cn-hangzhou
Project:
  Component: django
  Properties:
    Region: cn-hongkong
    Service:
      Name: serverless-china
    Function:
      Name: test
      Src: ./
```

例如一个Yaml中有多个Project：
```yaml
Name: MyWebsite
Version:
Stage: dev
Global:
  Region: cn-hangzhou
Projects:
  DjangoProject:
    Component: django
    Properties:
      Region: cn-hongkong
      Service:
        Name: serverless-china
      Function:
        Name: test
        Src: ./
  ReactProject:
    Component: react
    Properties:
      Region: cn-hongkong
      Backend: ${DjangoProject.Output.Url}
```

**Comment by rsonghuster** [comment]
1.  新升级的规范要保证完全向下兼容之前的格式
2. 个人觉的这个不错， 一个 yml 更有 app 的感觉， 组合层次感更强

**Reply by anycodes** [reply]
目前这个Yaml应该是不兼容之前的，但是可以s工具中单独做一个检测，来兼容之前的版本

**Comment by hanxie-crypto** [comment]
要不要直接统一都用projects ，可以方便统一规范

**Comment by anycodes** [comment]
```yaml
Name: MyWebsite
Stage: dev
Global:
  Region: cn-hangzhou
Applications:
  ApplicationName1: 
    Component: django
    Properties:
      Region: cn-hongkong
      Service:
        Name: serverless-china
      Function:
        Name: test
        Src: ./
```

**Comment by anycodes** [comment]
```yaml
Name: MyWebsite
Version: 规范的版本 # 默认最新的
Stage: dev
Global:
  Region: cn-hangzhou
Applications:
  ApplicationName1: 
    Component: fc@0.0.2
    Access: release
    Extends:
      deploy:
        - Hook: s build
          Src: ./
          Pre: false
    Properties:
      Region: cn-hongkong
      Service:
        Name: serverless-china
      Function:
        Name: test
        Src: ./
   
```

**Comment by anycodes** [comment]
```yaml
# s.yaml      s.dev.yaml   s.test.yaml
# s deploy    s deploy -t s.dev.yaml
# s deploy    s deploy -t s.test.yaml
Name: MyWebsite
Version: 规范的版本 # 默认最新的
Provider: alibaba # 全局变量，优先使用app里面的
Access: release # 全局变量，优先使用app里面的
Global:
  Region: cn-hangzhou
  SecretID: ${ENV(SecretId)}
Applications:
  APP-1: # 变量
    Component: fc@0.0.2
    Provider: alibaba
    Access: release
    Extends:
      deploy:
        - Hook: s build
          Src: ./
          Pre: false
    Properties:
      Region: cn-hongkong
      Service:
        Name: serverless-china  # serverless-china
      Function:
        Name: test
        Src: ./
  APP-2: # 变量
    Component: flask
    Properties:
      Src: /Users/jiangyu/WebstormProjects/serverless_test/anycodes
```
