### DISCUSSION TITLE
关于Yaml规范中，变量的说明

### DISCUSSION THREAD

**Discussion by anycodes** [Serverless-Devs/Serverless-Devs#433] [Show and tell]
目前，Serverless Devs 的 Yaml 中支持以下几种变量：

- 获取当前机器中的环境变量：${env(环境变量)}，例如${env(secretId)}
- 获取外部文档的变量：${file(路径)}，例如${file(./path)}
- 获取全局变量：${vars.*}
- 获取其他项目的变量：${projectName.props.*}
- 获取Yaml中其他项目的结果变量：${projectName.output.*}

随着项目的发展，需要额外增加几个变量：
1. config，获取当前配置的config变量：${config(AccountId)}
2. this，获取当前模块的信息，包括name和value两部分，以下面的Yaml为例：
```
edition: 1.0.0        #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: FullStack       #  项目名称

services:
  nextjs-portal: #  服务名称
    access: xxx-account1  #  秘钥别名，如果和项目的access相同，可省略
    component: vue-component  # 组件名称
    props: #  组件的属性值
      src: ./frontend_src
      url: url
    actions: # 自定义执行逻辑
      pre-deploy: # 在deploy之前运行
        - run: s exec -- publish  # 要运行的命令行
          path: ./backend_src # 命令行运行的路径
        - run: s build  # 要运行的命令行
          path: ./backend_src # 命令行运行的路径
      post-deploy: # 在deploy之后运行
        - run: s clean
          path: ./frontend_src
```
在`nextjs-portal`中:
- 使用`${this.name}`可以表示`nextjs-portal`;
- 使用`${this.access}`可以表示`xxx-account1`；
- 使用`${this.props.src}`可以表示` ./frontend_src`

另外，整个yaml中，都应该支持变量以及拼接。例如：
```
services:
  nextjs-portal: #  服务名称
    access: xxx-account1  #  秘钥别名，如果和项目的access相同，可省略
    component: vue-component  # 组件名称
    props: #  组件的属性值
      src: ./frontend_src
      url: url
    actions: # 自定义执行逻辑
      pre-deploy: # 在deploy之前运行
        - run: s exec ${this.props.url}  # 要运行的命令行
          path: ./backend_src # 命令行运行的路径
```
