### DISCUSSION TITLE
关于layer的优化

### DISCUSSION THREAD

**Discussion by heimanba** [Serverless-Devs/Serverless-Devs#462] [Ideas]
## 关于层layer的问题
1. custome runtime无法支持（4月份已经支持到了）
2. 无法查看层的详情(包含哪些包？具体版本是什么？)
3. 如何自动化将层，添加到应用？现在是一个层ID。。。非常难以理解，也非常难以使用

## 实现思路
1. 关于层的格式
```
- 
    layerName:         dankun-layer
    arn:               cb7bf1a9507a1b50c50ee6e8c7167141#dankun-layer#1
    version:           1
    description:       
    compatibleRuntime: 
      - nodejs12
```
2. 新建一个目录比如为layer, `npm init` 新建`package.json`，
然后安装相关依赖，比如 `npm i  egg -S`
```
layer
  package.json
```

3. `s.yaml`配置
```
services:
  helloworld: # 业务名称/模块名称
    component: fc
    actions:
      pre-deploy:
        - plugin: layer
           args:
               codeUri: ./layer
               name: egg-core
               update: true # 是否需要更新层，默认每次部署，不会重新更新层里面代码
               runtime:
                  - nodejs12
                  - python3
      props:
        region: ${vars.region} 
        service: ${vars.service}
```
帮您自动绑定 `layers`字段

## 相关ISSUE
https://github.com/devsapp/fc/issues/711
