### ISSUE TITLE
api部署失败

### ISSUE THREAD

**Issue by raykie** [Serverless-Devs/Serverless-Devs#179]
**Describe the bug**
部署函数失败，报错fail to get layer configuration。无论是否提前在阿里云控制台函数计算层管理中清空，都会有这个报错。在Linux命令行工具和Windows桌面版中都有这个问题。

**Screenshots**
![1629365617814_B553FCB7-6FD4-42c3-8391-7198E67D297E](https://user-images.githubusercontent.com/51851458/130313349-8f61714b-29b2-4261-864b-c6b0dab7549e.png)

**s.yaml**
```
edition: 1.0.0 #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: weatherApp #  项目名称
access: default #  秘钥别名

services:
  weather-app: #  服务名称
    component: devsapp/static-site # 这里引入的是相对路径，正式配置替换成你自己的component名称即可
    # actions:
    #   pre-deploy:
    #     - run: npm run build
    #       path: ./code
    props:
      targetStaticDir: 'code/dist' # 构建出的静态资源目录
      releaseDir: '_fc_release' # 用来发布到fc 上的目录，不需要修改
      service: 'website-test'
      function: 'website-test'
      port: 9000
      initializationTimeout: 60
      memorySize: 512
      timeout: 60
  api:
    component: devsapp/jamstack-api
    actions:
      pre-deploy:
        - run: npm install
          path: functions
    props:
      region: cn-hangzhou
      app:
        name: weather-app
      sourceCode: functions
      route:
        - /
```

**项目地址**
[https://github.com/raykie/weather-app](https://github.com/raykie/weather-app)

**Comment by wss-git** [comment]
publishLayerVersion 接口返回值发生了改变，之前arn 返回值是首字母大写，现在变为了小写，修改一下就好了

**Comment by wss-git** [comment]
项目地址
https://github.com/raykie/weather-app


s.yaml 建议将下载依赖的部分也加上
````
actions:
      pre-deploy:
        - run: npm i && npm run build
          path: ./code
````
