### ISSUE TITLE
s命令执行时候 兼容性问题

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#215]
s.yaml配置为
```
edition: 1.0.0
name: jamstack-website
access: default
vars:
  apiSourceCode: api
  domain: {{domain|官方提供一级域名，二级域名用户自己定义，最终生成：<你输入的域名>.resume.net.cn}}.resume.net.cn
  releaseCode: serverlessdevs-website/build # 最终构建的代码包
services:
  # api:
  #   component: devsapp/jamstack-api
  #   actions:
  #     pre-deploy:
  #       - run: npm install
  #         path: ./functions
  #   props:
  #     region: cn-hangzhou
  #     app:
  #       name: devs-http-demo #选填 默认 devs-http-demo
  #     sourceCode: functions
  #     route:
  #       - /
  jamstack-website:
    component: jamstack
    props:
      domain: ${vars.domain}
      favicon: false
      defaultApp: frontend
      apps:
        - name: frontend
          type: jamstack
          releaseCode: ${vars.releaseCode}
          paths:
            - /
          indexFile: index.html
          page404Url: 404.html       
```

可以认为这个s.yml其实是挂掉了，是不是给出一个友好的提示，无需所有的错误都爆出堆栈信息
