### ISSUE TITLE
env 环境变量支持

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#219]
支持`.env`的方式配置环境变量
在s.yaml格式为 `${env.hostName}`

**Comment by xsahxl** [comment]
![image](https://user-images.githubusercontent.com/21330840/135058305-590f556c-d6e3-49d9-9205-df66612df889.png)
目前s是支持的

测试：
- 添加环境变量myenv测试： export myenv=123
- s deploy 执行查看接收参数

**Comment by xsahxl** [comment]
测试
- 创建.env文件
```yaml
name=xiaoming
age=20
```
- s.yml格式大致如下
```yaml
edition: 1.0.0
access: "default"

services:
  website-starter:
    component: website
    props:
      bucket: "shl-bucket"
      src:
        env: ${env(name)}
        env1: ${env(age)}
        publishDir: ./src
        index: index.html
      region: cn-hangzhou
      hosts:
        - host: auto
```
- s deploy --debug 查看接收参数
![image](https://user-images.githubusercontent.com/21330840/135061831-249c7c89-9d73-40ad-8d13-3e0ea91ebe4d.png)
