### ISSUE TITLE
yaml中变量引用报错

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#236]
引用`vars.region`报错
```
edition: 1.0.0
name: transform_fun
access: default
vars:
  region: '***'
services:
  fc-kjzl-kjzl:
    component: devsapp/fc
    props:
      region: ${vars.region}
```
![image](https://user-images.githubusercontent.com/5129967/137659894-509e7ef1-8e9d-4175-8c33-56ecebc01cce.png)
