### ISSUE TITLE
多项目部署时 inputs 入参会被组件代码篡改

### ISSUE THREAD

**Issue by wss-git** [Serverless-Devs/Serverless-Devs#286]
````
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: app       #  项目名称
access: yunxi

vars:
  region: cn-qingdao
  service:
    name: serverless-devs-custom-nodejs
    description: 'Serverless Devs示例: Express.js framework service'
    logConfig: auto
  triggers:
    - name: httpTrigger
      type: http
      config:
        authType: anonymous
        methods:
          - GET
  customDomains:
    - domainName: auto
      protocol: HTTP
      routeConfigs:
        - path: '/*'

services:
  express:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: express
        description: express
        runtime: custom
        ossBucket: wss-demo
        codeUri: ./express
        handler: index.handler
        memorySize: 256
        timeout: 30
        environmentVariables:
          ENABLE_TS_REMOTE_DEBUG: "true"
      triggers: ${vars.triggers}
      customDomains: ${vars.customDomains}
  
  koa:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: koa
        description: koa
        runtime: custom
        ossBucket: wss-demo
        codeUri: ./koa
        handler: index.handler
        memorySize: 256
        timeout: 30
        environmentVariables:
          ENABLE_TS_REMOTE_DEBUG: "true"
      triggers: ${vars.triggers}
      customDomains: ${vars.customDomains}
````
测试结果：直接操作 inputs 会污染下次执行的入参，但是在组件的入口处深拷贝一下入参就不会有问题。

更详细关联问题：https://github.com/devsapp/fc/issues/371
