### ISSUE TITLE
error: unknown command deploy

### ISSUE THREAD

**Issue by realkimmy** [Serverless-Devs/Serverless-Devs#292]
**Describe the bug**
error: unknown command deploy.

**Screenshots**
<img width="997" alt="截屏2021-11-05 20 20 31" src="https://user-images.githubusercontent.com/19725091/140593197-974c1ddd-ad2c-49cb-a151-77ac21596a58.png">

**Desktop (please complete the following information):**
 - Version: @serverless-devs/s: 2.0.92, @serverless-devs/core: 0.1.10, darwin-x64, node-v12.21.0

**Additional context**

**Comment by heimanba** [comment]
请问下您是执行了 `s deploy`指令吗
麻烦能提供下您的 s.yaml配置吗，或者您可以加入钉钉群  33947367  获得快速的支持

**Comment by realkimmy** [comment]
@heimanba 参考的这篇[文章](https://help.aliyun.com/document_detail/295926.html)，没有s.yaml配置

**Comment by heimanba** [comment]
@realkimmy ，这个文章是针对github CICD 场景哈，但是需要当前有个 serverless-devs的项目(跟目录需要有s.yaml)。否则执行s deploy 找不到对应的文件哈

**Comment by realkimmy** [comment]
现在问题是s deploy命令找不到

**Comment by realkimmy** [comment]
难道是因为没有s.yaml文件，所以s deploy命令找不到？

**Comment by heimanba** [comment]
@realkimmy 是的哈，因为deploy的能力是s.yaml提供的。可以认为serverless-devs是一个多云的工具。这里deploy 确切来说是 `devsapp/fc`这个组件提供的能力
```
edition: 1.0.0
name: fcDeployApp
access: "default"

services:
  fc-deploy-test:
    component: devsapp/fc
    props:
      region: cn-hangzhou
```
