### ISSUE TITLE
是否可以对组件运行新增 retry 次数

### ISSUE THREAD

**Issue by wss-git** [Serverless-Devs/Serverless-Devs#316]
需求：在 component 同级新增一个 retry 参数

场景：下面 yaml 文件，首次部署常常会遇到错误 400，原因是日志资源不可用， 但是多重试几次就成功了【当然，这是体验不好，会慢慢优化】，如果用户比较熟悉的组件的时候，他们就需要多手动尝试几次。

问题延伸：如果在用户熟悉我们运行逻辑和组件的时候，我们是不是可以帮助用户去做这些体验式的优化，例如这个场景，新增 retry 字段，准对某个组件失败的话多尝试几次。
````
edition: 1.0.0
name: slsApp

vars:
  regionId: cn-shenzhen

services:
  sls-test:
    component: devsapp/sls
    props:
      regionId: ${vars.regionId}
      project: uid-cn-shenzhen-logproject-test-fc
      description: wss
      logstore:
        - name: fc-service-fc-test-logstore
        - name: fc-service-fc-test-logstore-2
          option:
            ttl: 333
            shardCount: 2

  fc-test:
    component: devsapp/fc
    retry: 1
    props:
      regionId: ${vars.regionId}
      service:
        name: fc-test
        description: demo for fc component
        internetAccess: true
        logConfig:
          project: ${sls-test.output.project}
          logstore: ${sls-test.output.logstore[0].name}
````
