### ISSUE TITLE
TypeError: h is not a constructor

### ISSUE THREAD

**Issue by realkimmy** [Serverless-Devs/Serverless-Devs#325]
**Describe the bug**
运行`s deploy`报错

**Screenshots**

```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: FlutterBoilerplateStore       #  项目名称
access: flutter_boilerplate_store  #  秘钥别名

services:
  flutter-boilerplate-store: # 服务名称
    component: ./  # 组件名称
    actions:
      pre-deploy: # 在deploy之前运行
        - run: yarn install && yarn build  # 要运行的命令行
          path: . # 命令行运行的路径

    props: # 组件的属性值
      region: cn-hongkong
      service:
        name: flutter-boilerplate-store
        description: 'Serverless Devs示例: Express.js framework service'
      function:
        name: store
        description: 'Store'
        # customContainerConfig:
        # command: '["/mnt/auto/express/start.sh"]' # 代码包传入 nas 部署，同时也要注意创建start.sh文件，如果没有此处customContainerConfig/command配置，系统会默认创建该配置和start.sh
        # command: '["./start.sh"]' # 代码包直接放入 container
        code:
          src: .
          excludes:
            - .s
            - .git
            - node_modules
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: '/*'

```

**Desktop (please complete the following information):**

@serverless-devs/s: 2.0.92, darwin-x64, node-v12.21.0

**Additional context**

**Comment by heimanba** [comment]
看起来组件名称不对哈,换成下面试试
```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: FlutterBoilerplateStore       #  项目名称
access: flutter_boilerplate_store  #  秘钥别名

services:
  flutter-boilerplate-store: # 服务名称
    component: devsapp/fc  # 组件名称
    actions:
```

**Comment by realkimmy** [comment]
Error: 'codeUri' and 'ossKey' can not be empty in function config at the same time.

**Comment by realkimmy** [comment]
```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: FlutterBoilerplateStore       #  项目名称
access: flutter_boilerplate_store  #  秘钥别名

services:
  flutter-boilerplate-store: # 服务名称
    component: devsapp/fc  # 组件名称
    actions:
      pre-deploy: # 在deploy之前运行
        - run: yarn build  # 要运行的命令行
          path: . # 命令行运行的路径
        - run: zip -r code.zip . -x 'node_modules/*' -x '*.git*' -x '*.idea*' -x '*.vercel*' -x '*.s*'  # 要运行的命令行
          path: . # 命令行运行的路径

    props: # 组件的属性值
      region: cn-hongkong
      service:
        name: 'flutter-boilerplate'
        description: 'Flutter Boilerplate'
      function:
        name: store
        description: 'Flutter Boilerplate Store'
        runtime: 'nodejs12'
        codeUri: './code.zip'
      triggers:
        - name: httpTrigger
          type: http
          qualifier: xxx
          config:
            authType: function
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: 'fc.store.gitterapp.com'
          protocol: 'HTTP, HTTPS'
          routeConfigs:
            - path: '/*'
          certConfig:
            certName: 'fc-store'
            privateKey: ''
            certificate: ''

```

**Comment by anycodes** [comment]
错误信息：FCAliasNotFoundError: POST /services/flutter-boilerplate/functions/store/triggers failed with 404. requestid: 1da4609b-1963-49b2-a4d2-c8da575c6ae0, message: alias 'xxx' of service 'flutter-boilerplate' does not exist.

大概意思是说，在请求这个接口的时候`/services/flutter-boilerplate/functions/store/triggers`，发现别名`xxx`并不存在

所以此时可以看一下触发器配置，是否使用了xxx:

```
triggers:
        - name: httpTrigger
          type: http
          qualifier: xxx
          config:
            authType: function
            methods:
              - GET
              - POST
              - PUT
              - DELETE
```

所以只需要删除：
```
 qualifier: xxx
```

就没问题了，可以试一下

**Comment by realkimmy** [comment]
FCInvalidArgumentError: POST /custom-domains failed with 400. requestid: 1437f0ce-6150-49f2-b7a4-13d1964037da, message: 'private key' has to be in PEM format.

**Comment by realkimmy** [comment]
我从阿里云申请的免费证书

**Comment by realkimmy** [comment]
```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: FlutterBoilerplateStore       #  项目名称
access: flutter_boilerplate_store  #  秘钥别名

services:
  flutter-boilerplate-store: # 服务名称
    component: devsapp/fc  # 组件名称
    actions:
      pre-deploy: # 在deploy之前运行
        - run: yarn build  # 要运行的命令行
          path: . # 命令行运行的路径
        - run: zip -r code.zip . -x 'node_modules/*' -x '*.git*' -x '*.idea*' -x '*.vercel*' -x '*.s*'  # 要运行的命令行
          path: . # 命令行运行的路径

    props: # 组件的属性值
      region: cn-hongkong
      service:
        name: 'flutter-boilerplate'
        description: 'Flutter Boilerplate'
      function:
        name: store
        description: 'Flutter Boilerplate Store'
        runtime: 'nodejs12'
        codeUri: './code.zip'
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: function
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: 'fc.store.gitterapp.com'
          protocol: 'HTTP,HTTPS'
          routeConfigs:
            - path: '/*'
          certConfig:
            certName: 'fc-store'
            privateKey: '.cert/fc-cert.key'
            certificate: '.cert/fc-cert.pem'

```

**Comment by wss-git** [comment]
目前函数计算仅支持 pem 格式的证书，您试试将 fc-cret.key 转化成 pem 格式的证书试试呢

````
openssl rsa -in .cert/fc-cert.key -out .cert/fc-privateKey.pem
````

**Comment by wss-git** [comment]
目前函数计算仅支持 pem 格式的证书，您试试将 fc-cret.key 转化成 pem 格式的证书试试呢

````
openssl rsa -in .cert/fc-cert.key -out .cert/fc-privateKey.pem
````

**Comment by wss-git** [comment]
目前函数计算仅支持 pem 格式的证书，您试试将 fc-cret.key 转化成 pem 格式的证书试试呢

````
openssl rsa -in .cert/fc-cert.key -out .cert/fc-privateKey.pem
````

**Comment by realkimmy** [comment]
```
[2021-11-18 07:59:48] [INFO] [FC-DEPLOY] - Checking Function store exists
[2021-11-18 07:59:48] [INFO] [FC-DEPLOY] - Checking Trigger httpTrigger exists
[2021-11-18 07:59:48] [INFO] [FC-DEPLOY] - Creating custom domain: fc.store.gitterapp.com
[2021-11-18 07:59:48] [INFO] [FC-DOMAIN] - Creating custom domain: fc.store.gitterapp.com
Retrying custom domain: create fc.store.gitterapp.com, retry 1 time
Retrying custom domain: create fc.store.gitterapp.com, retry 2 time
Retrying custom domain: create fc.store.gitterapp.com, retry 3 time
Retrying custom domain: create fc.store.gitterapp.com, retry 4 time
✖ Project flutter-boilerplate-store failed to execute:

TraceId:     149d997e0d791637222398729
Environment: @serverless-devs/s: 2.0.92, @serverless-devs/core: 0.1.13, darwin-x64, node-v12.22.7
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues

ERROR:
FCDomainNameNotResolvedError: POST /custom-domains failed with 400. requestid: 64ebc914-63d5-4e4e-a305-80ad18af06e4, message: domain name 'fc.store.gitterapp.com' has not been resolved to your FC endpoint, the expected endpoint is '1201321425474702.cn-hongkong.fc.aliyuncs.com. or 1201321425474702.cn-hongkong-internal.fc.aliyuncs.com.'.

```

**Comment by realkimmy** [comment]
是需要加DNS吗？

**Comment by wss-git** [comment]
需要 dns 解析的，解析的端点是

````
# 公网访问
1201321425474702.cn-hongkong.fc.aliyuncs.com
# 内网访问
1201321425474702.cn-hongkong-internal.fc.aliyuncs.com
````

**Comment by realkimmy** [comment]
@wss-git 还有一个问题就是，我访问https://fc.store.gitterapp.com/mobile/，应该返回一个网页，实际返回如下错误

```
{
  "ErrorCode": "MissingRequiredHeader",
  "ErrorMessage": "required HTTP header Date was not specified"
}
```

**Comment by wss-git** [comment]
dns 绑定哪个地址？  是这个吗：1201321425474702.cn-hongkong.fc.aliyuncs.com

如果不是换成这个试试呢

**Comment by wss-git** [comment]
知道原因了，authType: function 是需要签名认证的

````
triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
````

**Comment by realkimmy** [comment]
```
{
  "errorMessage": "Module '/code/index.js' is missing.",
  "errorType": "FunctionUnhandledError: ImportModuleError",
  "stackTrace": [
    "ImportModuleError: Module '/code/index.js' is missing."
  ]
}
```

**Comment by realkimmy** [comment]
必须在项目根目录下有一个index.js文件？

**Comment by heimanba** [comment]
假设配置如下
```
function:
        runtime: nodejs12
        codeUri: ./code
        handler: index.handler
```
具体执行的函数为，code 目录下面，index.js里面有个handler函数。可以按照这个来排查下哈.或者初始化下demo `s init fc-http-nodejs`体验下流程哈

**Comment by realkimmy** [comment]
ok, 3q

**Comment by heimanba** [comment]
@realkimmy 大佬，可以加入我们的钉钉群哈。33947367 有问题可以随时在里面提问。随时有同学支持的

**Comment by realkimmy** [comment]
我启动的是express服务，也需要到处handler？

**Comment by heimanba** [comment]
您可以使用customer runtime形式部署，具体就是写一个 bootstrap 的文件。把启动脚本放进去

**Comment by realkimmy** [comment]
```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: FlutterBoilerplateStore       #  项目名称
access: flutter_boilerplate_store  #  秘钥别名

services:
  flutter-boilerplate-store: # 服务名称
    component: devsapp/express  # 组件名称
    actions:
      pre-deploy: # 在deploy之前运行
        - run: yarn install  # 要运行的命令行
          path: .
        - run: yarn build  # 要运行的命令行
          path: . # 命令行运行的路径
        - run: zip -r code.zip . -x 'node_modules/*' -x '*.git*' -x '*.idea*' -x '*.vercel*' -x '*.s*'  # 要运行的命令行
          path: . # 命令行运行的路径

    props: # 组件的属性值
      region: cn-hongkong
      service:
        name: 'flutter-boilerplate'
        description: 'Flutter Boilerplate'
      function:
        name: store
        description: 'Flutter Boilerplate Store'
        code:
          src: '.'          # 本地路径
          excludes:
            - .s
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: 'fc.store.gitterapp.com'
          protocol: 'HTTP,HTTPS'
          routeConfigs:
            - path: '/*'
          certConfig:
            certName: 'fc-store'
            privateKey: '.cert/fc-privateKey.pem'
            certificate: '.cert/fc-cert.pem'

```

**Comment by realkimmy** [comment]
还是报上面的错

```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: FlutterBoilerplateStore       #  项目名称
access: flutter_boilerplate_store  #  秘钥别名

services:
  flutter-boilerplate-store: # 服务名称
    component: devsapp/fc  # 组件名称
    actions:
      pre-deploy: # 在deploy之前运行
        - run: yarn build  # 要运行的命令行
          path: . # 命令行运行的路径
        - run: zip -r code.zip . -x 'node_modules/*' -x '*.git*' -x '*.idea*' -x '*.vercel*' -x '*.s*'  # 要运行的命令行
          path: . # 命令行运行的路径

    props: # 组件的属性值
      region: cn-hongkong
      service:
        name: 'flutter-boilerplate'
        description: 'Flutter Boilerplate'
      function:
        name: store
        description: 'Flutter Boilerplate Store'
        runtime: 'custom'
        codeUri: './code.zip'
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: 'fc.store.gitterapp.com'
          protocol: 'HTTP,HTTPS'
          routeConfigs:
            - path: '/*'
          certConfig:
            certName: 'fc-store'
            privateKey: '.cert/fc-privateKey.pem'
            certificate: '.cert/fc-cert.pem'
```
