### ISSUE TITLE
Aws lambda报错 An update is in progress for resource

### ISSUE THREAD

**Issue by shaoyun** [Serverless-Devs/Serverless-Devs#410]
第一次部署会成功，第二次部署的时候如下提示，如果直接remove掉，然后部署也会直接成功
```
❯ s deploy
Starting ...
[2022-01-27 10:48:40] [INFO] [S-CLI] - It is detected that your project has the following projects < level2,level4 > to be execute
[2022-01-27 10:48:40] [INFO] [S-CLI] - Start executing project level2
Starting deploy of AWS Lambda "alert-center-aws-notice" to the AWS region "ap-southeast-1".
Start compressing code.
Packing ...
Package complete.
Successful compression code.
✖ Project level2 failed to execute:

ERROR:
The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:ap-southeast-1:xxxxx:function:alert-center-aws-notice

TraceId:     34363bd055061643280528259
Environment: @serverless-devs/s: 2.0.99, core: 0.1.28, s-home: /Users/shaoyun/.s, darwin-x64, node-v14.17.1
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues

Please copy traceId: 34363bd055061643280528259 and join Dingding group: 33947367 for consultation.
You can run 's clean --all' to clean Serverless devs.
```
配置如下

```
edition: 1.0.0
name: alert-center-aws-notice
access: default
vars:
  region: ap-southeast-1
  role: arn:aws:iam::xxxxx:role/fc-sns-alert-role
  service:
    name: noticeService
    description: Alert center notice service
services:
  level2:
    component: devscomp/lambda
    props:
      region: ${vars.region}
      function:
        name: alert-center-aws-notice
        description: ${vars.service.description}
        role: ${vars.role}
        runtime: nodejs14.x
        codeUri: ./code
        handler: index.handler
        memorySize: 128
        timeout: 60
        environment:
          variables:
            - Key: ALERT_LEVEL
              Value: "2"
  level4:
    component: devscomp/lambda
    props:
      region: ${vars.region}
      function:
        name: alert-center-aws-notice-high-level
        description: ${vars.service.description}
        role: ${vars.role}
        runtime: nodejs14.x
        codeUri: ./code
        handler: index.handler
        memorySize: 128
        timeout: 60
        environment:
          variables:
            - Key: ALERT_LEVEL
              Value: "4"
```
