### ISSUE TITLE
vars变量支持复杂结构

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#411]
## yaml配置如下
```
edition: 1.0.0
name: serverless-devs
access: "default"

vars:
  region: ap-southeast-1
  service:
    name: serverless-devs-docs
    description: "hello world by serverless devs"
 

services:
  serverless-devs-docs-async:
    component: fc
    actions:
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: async-github-docs
        environmentVariables:
          serviceName: ${vars.service.name}
```

这里 **serviceName: ${vars.service.name}** 为空，并不生效,理论上也需要生效的
