### ISSUE TITLE
校验edition版本

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#416]
我们现在的s.yaml配置如下
```
edition: 1.0.0
access: "serverless-devs"

services:
  website-starter:
    component: oss
```
这里我们的规范是根据edition来定。后面会支持2.0.0所以必须强校验edition这个关键字，假设不存在，或者这个edition不准确，需要直接报错，告诉用户
