### ISSUE TITLE
【优化】在组件可以获取整个项目的执行情况

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#419]
## 现状
Serverless-Devs是一个多应用的管理工具，每个应用的能力通过组件来提供。在组件的指令会接受一个`inputs`的指令，这个inputs 只是静态值，但是也有诉求希望能够动态的获取当前的执行情况。这样的话：组件可以根据当前的执行的情况来进行一些操作。

#### 场景
有个直接的场景，就是比如一个项目（s.yaml）中有20个函数计算的函数应用。这20个应用的service配置都是一致的，当前情况会部署20次。部署时长比较久，用户体验不太好。

## 思考 && 探索
每个组件的指令比如(deploy) 都会接受一个参数`inputs`，这个参数是静态的，一般包含下面几个信息
- project 相关信息
- 组件的props,是用户输入的信息
- access, 相关的密钥

这时候并没有执行过程中的动态信息。比如我的s.yaml 有以下配置，他们的service 的配置都是相同的
```
edition: 1.0.0
name: serverless-devs-app
access: "default"
vars: # 全局变量
  service:
    name: serverless-devs-ui
    description: "Serverless Devs Web Framework Service"

services:
  serviceA:
      props: # 组件的属性值
        service: ${vars.service}
  serviceB:
     props: # 组件的属性值
        service: ${vars.service}
  serviceC:
     props: # 组件的属性值
        service: ${vars.service}
  serviceD:
      props: # 组件的属性值
        service: ${vars.service}
```
运行的顺序如下： `serviceA`-> `serviceC`->`serviceB`->`serviceD`
这里假设我现在正在执行 `serviceB`的时候,我能知道`serviceA`以及`serviceC`都已经执行了。我就可以直接跳过部署的过程。

## 方案
`Serverless Devs`的`CLI`在执行的时候能够收集到所有执行信息，将当前执行的信息也就是上面讲的`inputs`放在执行队列中。比如我在执行到`serviceB`的时候在`inputs`有个字段`executedList`,数据结构如下
```
inputs: {
  ....,
  executedList: [serviceAInputs, serviceCInputs]
}
```
这时候组件就可以拿到这些信息，来做特定的优化
