### ISSUE TITLE
how to specify oss trigger

### ISSUE THREAD

**Issue by newbaluku** [Serverless-Devs/Serverless-Devs#421]
trying to specify an OSS trigger but getting 400 error:

✔ Checking Service, Function, Triggers (2.4s)
✖ Creating Service, Function, Triggers (1.19s)
✖ Creating Service, Function, Triggers (0.8s)
✖ Creating Service, Function, Triggers (0.41s)
✖ Project fc-sxfi-api-msgbox-dev-sxfi-api-msgbox-dev-app failed to execute:

ERROR:
POST /services/sxfi-api-msgbox-dev/functions/sxfi-api-msgbox-dev-app/triggers failed with 400. requestid: da3d9d99-5b45-4a58-8dda-1c172e31f116, message: invalid OSS trigger config.

```
edition: 1.0.0
name: msgbox
access: default
vars:
  region: ap-southeast-1
services:
  fc-msgbox-dev-msgbox-dev-app:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service:
        name: msgbox-dev
        description: msgbox-dev service
        role:
          name: msgbox-devDefaultRole
          policies:
            - AliyunLogFullAccess
        internetAccess: true
        logConfig: auto
      function:
        name: msgbox-dev-app
        description: msgbox-dev app
        handler: index.handler
        timeout: 30
        memorySize: 1024
        runtime: nodejs12
        environmentVariables:
          NODE_ENV: development
        instanceConcurrency: 5
        codeUri: ./
      triggers:
        - name: ossTrigger
          type: oss
          config:
            bucketName: msgbox-sg-dev
            events:
              - oss: oss:ObjectCreated:PutObject
            filter:
              Key:
                Prefix: /
                Suffix: ''
```

would like to find out what is wrong as there isn't much doc on how to specify it properly.
