### ISSUE TITLE
是否支持一个service对应多个functions

### ISSUE THREAD

**Issue by M09Ic** [Serverless-Devs/Serverless-Devs#426]
类似serverless framework, 每个service下可以指定多个functions. 
翻阅了下文档和example, 没有找到类似案例, 不知道是否可行.

**Comment by wss-git** [comment]
可以参考一下这个

````
edition: 1.0.0
name: hello-world-app
access: "{{ access }}"

vars: # 全局变量
  region: cn-hangzhou
  service:
    name: hello-world-service
    description: 'hello world by serverless devs'

services:
  helloworld: # 业务名称/模块名称
    component:  fc
    props: #  组件的属性值
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: event-nodejs12
        description: 'hello world by serverless devs'
        runtime: nodejs12
        codeUri: ./code
        # ossBucket:
        # ossKey:  # conflict with codeUri
        handler: index.handler
        memorySize: 128
        timeout: 60
  next-function: # 第二个函数的案例，仅供参考
    # 如果在当前项目下执行 s deploy，会同时部署模块：
    #   helloworld：服务hello-world-service，函数cpp-event-function
    #   next-function：服务hello-world-service，函数next-function-example
    # 如果想单独部署当前服务与函数，可以执行 s + 模块名/业务名 + deploy，例如：s next-function deploy
    # 如果想单独部署当前函数，可以执行 s + 模块名/业务名 + deploy function，例如：s next-function deploy function
    # 更多命令可参考：https://github.com/devsapp/fc/tree/jiangyu-docs/docs#文档相关
    component: fc
    props:
      region: ${vars.region}
      service: ${vars.service} # 应用整体的服务配置
      function: # 定义一个新的函数
        name: next-function-example
        description: 'hello world by serverless devs'
````
