### ISSUE TITLE
可以支持一个服务同时部署到多个地域吗？

### ISSUE THREAD

**Issue by pilaoda** [Serverless-Devs/Serverless-Devs#458]

**Comment by heimanba** [comment]
可以看下这里的案例，https://github.com/devsapp/start-realwrold/tree/master/src

比如设置s-hangzhou.yaml
```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: functionApp       #  项目名称
access: default  #  秘钥别名

vars: # 全局变量
  region: "cn-hangzhou"
  service:
    name: "service-a"
    description: 'Serverless Devs Web Framework Service'

services:
  service-a: 
    props: # 组件的属性值
      region: ${vars.region}
      service: ${vars.service}
```
执行时候 为 `s deploy -t s-hangzhou.yaml`

部署到深圳的region可以为 s-shenzhen.yaml
```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: functionApp       #  项目名称
access: default  #  秘钥别名

vars: # 全局变量
  region: "cn-shenzhen"
  service:
    name: "service-a"
    description: 'Serverless Devs Web Framework Service'

services:
  service-a: 
    props: # 组件的属性值
      region: ${vars.region}
      service: ${vars.service}
```
执行时候 为 `s deploy -t s-shenzhen.yaml`
