### ISSUE TITLE
Deploy 和 remove 操作不是互斥的。

### ISSUE THREAD

**Issue by TonySFU** [Serverless-Devs/Serverless-Devs#52]
1.每次Deploy 都会在一个服务下新建一个新的函数，并且绑定一个新的临时域名。
2.Remove 操作无法停止正常工作的函数，只能简单的移除服务。

可以考虑将这两个API更加完整包装

**Comment by anycodes** [comment]
您这里具体使用的是那个组件呢？方便脱敏一下yml文件，发一下么？

**Comment by TonySFU** [comment]
```yaml
HexoComponent:
  Component: hexo
  Provider: alibaba
  Extends:
    deploy:
      - Hook: npm install --production
        Path: ./src
        Pre: true
      - Hook: npm run build
        Path: ./src
        Pre: true
  Properties:
    Region: 'cn-hangzhou'
    CodeUri: './src'
    Detail:
      Service:
        Name: demo
```
执行 `~ s remove`

```bash
Start ...
It is detected that your project has the following project/projects < HexoComponent > to be execute
Start executing project HexoComponent
Tags empty, skip deleting.
Start deploying domains ...
Function not exists, skip deleting trigger
Deleting function demo@s-function-1615572956463
Function demo@s-function-1615572956463 not exists.
Deleting service demo
Error: Unable to delete service demo: DELETE /services/demo failed with 409. requestid: a11d6225-e64e-4782-ac6d-a0ce6f45c98b, message: service 'demo' has active 'functions'.
Project HexoComponent failed to execute
End of method: remove

********** The operation was not fully successful **********
> Project Run Error: HexoComponent
Error: Error: Unable to delete service demo: DELETE /services/demo failed with 409. requestid: a11d6225-e64e-4782-ac6d-a0ce6f45c98b, message: service 'demo' has active 'functions'.
```

再次执行 `s HexoComponent remove`

```bash
Start ...
Tags empty, skip deleting.
Start deploying domains ...
Function not exists, skip deleting trigger
Deleting function demo@s-function-1615573280162
Function demo@s-function-1615573280162 not exists.
Deleting service demo
Error: Unable to delete service demo: DELETE /services/demo failed with 409. requestid: 08cf4303-f301-4b82-bdb2-b9f8fad51024, message: service 'demo' has active 'functions'.

********** The operation was not fully successful **********

Error: Unable to delete service demo: DELETE /services/demo failed with 409. requestid: 08cf4303-f301-4b82-bdb2-b9f8fad51024, message: service 'demo' has active 'functions'.
```

问题定位：
执行remove 操作的时候会生成新的function id，但不是真正的function，这部分的代码好像没有开源，只能猜个大概的实现方式。
