### ISSUE TITLE
s.yaml支持模板引擎

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#529]
编写应用模板时很可能有这种情况：
1. 用户可以自己指定vpc配置，如果指定了就用自定义的，没指定就用auto
2. 用户可以自定指定nas配置，如果指定了就用自定义的，没指定就用auto
3. 如果关联了环境，就使用环境提供的配置
...

因此，需要在一个应用模板中具备一些逻辑能力，否则就需要写多个应用模板。
比较通用的方式是在s.yaml中可以支持模板引擎，目前[Jinja2](https://jinja.palletsprojects.com/en/3.1.x/)是比较受欢迎的，但Jinja是Python生态的，调研了下Nodejs的模板引擎，目前觉得最适合的是[nunjucks](http://mozilla.github.io/nunjucks/getting-started.html)，是在Jinja基础上的Nodejs实现，兼容Jinja原生的写法，功能也比较全。

```yaml
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: framework         #  项目名称
access: "{{ access }}"       #  秘钥别名

vars:
  region: {{ region }}
  service:
    name: {{ serviceName }}
    description: 'Serverless Devs Web Framework Service'
  {% if !vpcConfig %}
    vpcConfig: auto
  {% else %}
    vpcConfig:
      securityGroupId: {{ vpcConfig.securityGroupId }}
      vpcId: {{ vpcConfig.vpcId }}
      vswitchIds: #数组
      {% for id in vpcConfig.vswitchIds %}
        - {{ id }}
      {% endfor %}
  {% endif %}
  {% if !nasConfig %}
    nasConfig: auto
  {% else %}  
    nasConfig:
      userId: {{ nasConfig.userId if nasConfig.userId else 10003 }}
      groupId: {{ nasConfig.userId if nasConfig.userId else 10003 }}
      mountPoints:
        - serverAddr: {{ nasConfig.serverAddr }}
          nasDir: {{ nasConfig.nasDir }}
          fcDir: {{ nasConfig.fcDir }}
  {% endif %}
    
services:
  fc-nas-filemgr: # 业务名称/模块名称
    component: fc # 组件名称
    actions:
      post-deploy:
        # 请注意这里上传的路径，如果之前已经挂载了这个nas，并且上传过这个文件夹，会导致文件的覆盖
        - component: fc nas upload -r code/kodbox/ /mnt/auto/.fc-nas-filemgr
    props: # 组件的属性值
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: "{{ functionName }}"
        description: 'Serverless Devs Web Framework kodbox  Function'
        codeUri: './code'
        runtime: custom
        timeout: 7200
        memorySize: 3072
        instanceConcurrency: 16
        customRuntimeConfig:
          command:
            - bash
          args:
            - '-c'
            - '/code/start.sh'
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - HEAD
                - OPTIONS
```
