### ISSUE TITLE
当一个函数存在多个环境变量时, 提示 format is incorrect

### ISSUE THREAD

**Issue by iugo** [Serverless-Devs/Serverless-Devs#535]
**Describe the bug**

当一个函数存在多个环境变量时, 提示 `format is incorrect`.

比如 yaml:

```
function:
  name: for-deno
  environmentVariables:
    DENO_DIR: /tmp/deno_dir
    DENO_DIR: /tmp/deno_dir
```

预期为, 提醒不支持重复的环境变量. 或者, 使用后者覆盖前者.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: macOS
 - Version: @serverless-devs/s: 2.1.1, core: 0.1.41, s-home: /Users/zheren/.s, darwin-x64, node-v16.10.0

**Additional context**
