### ISSUE TITLE
模板引擎支持自定义filter以及dry-run能力

### ISSUE THREAD

**Issue by lowkeyrd** [Serverless-Devs/Serverless-Devs#543]
**支持自定义filter**
需求场景：
1. 函数要通过内网访问OSS或者ACR来省去流量开销，需要函数部署在和OSS或者ACR相同的region，此时最理想的方案是parameter只透出一个endpoint，自动解析出函数的region，例如：
```yaml
region: {{ endpoint | parseRegion }}
```
2. 函数需要连接数据库，比如RDS、HBASE，需要函数部署在和数据库实例相同的vswitch、vpc内，现在需要用户人肉填写这些参数非常不便，最理想的方式是通过数据库实例ID 去查询所在的region、vpc、vswitch，例如：
```yaml
vars:
  output: {{ instanceId | parseRDS }
...
region: ${vars.output.region}
service:
  vpcConfig: 
    vpcId: ${vars.output.vpcId}
    vswitchIds: 
      {{each vars.output.vswitchIds}}
      - {{$value}}
      {{/each}}
```
3. payload基本都约定传递个json string，但是对用户透出的还是具体的object，需要在payload中将object转成json string，例如：
```yaml
vars:
  SINK_CONFIG: 
     accessKey: "{{accessKey}}"
     accessSecret: "{{accessSecret}}"
     project: "{{maxcomputeProject}}"
     endpoint: "{{maxcomputeEndpoint}}"
     table: "{{maxcomputeTable}}"
  SOURCE_CONFIG:
    hbase_url: "{{hbaseEndpoint}}"
    user: "{{username}}"
    password: "{{password}}"
    namespace: "{{namespace}}"
    table_name: "{{tableName}}"
...
triggers:
  - name: cron
    type: timer
    config:
      payload: {{ vars | jsonString }}
```
因此，需要利用 [模板引擎的filter能力](https://aui.github.io/art-template/docs/syntax.html#Filters) 来支持一些内置filter以及自定义filter

**应用模板dry-run能力**
开发一个应用模板，完成publish.yaml和s.yaml的编写后，需要本地验证下渲染出的s.yaml是否正确，现在需要先发布应用再执行s init，效率比较低，需要支持一种dry-run的能力，本地开发完后 执行 s dry-run --parameters 就可以检验schema并生成s.yaml
