### ISSUE TITLE
服务输出结果的缓存

### ISSUE THREAD

**Issue by hanxie-crypto** [Serverless-Devs/Serverless-Devs#547]
**Is your feature request related to a problem? Please describe.**
当我们部署一些复杂的Serverless架构应用时候，service之间会有上下文的依赖关系，比如网关的后端服务部分依赖前面某个函数服务的输出，现在devs已经实现了整体部署的依赖解析，但当我只想部署单个服务的时候（只有单个服务发生了变更），往往需要全部重新把所有服务部署一遍，浪费时间且容易对其他的服务产生影响。

**Describe the solution you'd like**
希望有上下文依赖的服务独立部署的时候依然正常可用，需要devs支持服务部署结果的共享存储，将依赖解耦到共享存储。

**Describe alternatives you've considered**
devs 需要将依赖解析，将每个服务的结果存储成一个服务和结果的映射数据结构，每次加载服务的时候先读取该映射结构， 改数据结构中的任意一个服务重新部署后都应当重新刷新数据，让依赖他的服务拿到最新的数据，通过这种方式实现每个服务的单独部署

**Additional context**
如下，gateway部分依赖了http-control-center的输出结果，每次部署gateway都需要先部署一下http-control-center
```
services:
  http-control-center:
    component: devsapp/fc # 组件名称
    actions: 
      pre-deploy: # 安装好依赖后可以注释掉
        - run: npm install
          path: http-control-center
    props:
      region: ${vars.region}
      service:
        name: barrage-control
        description: 弹幕效果后台
        internetAccess: true
        role:
          name: tablestore
          policies:
            - AliyunOTSFullAccess
      function:
        name: barrage-control
        environmentVariables:
          endpoint: ${vars.tablestore.endpoint}
          instance: ${vars.tablestore.instance}
          notifyUrl: http://${vars.domain}/notify
        description: 
        runtime: nodejs12
        codeUri: ./http-control-center
        handler: index.handler
        initializer: index.initializer
        memorySize: 128
        timeout: 60
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
  gateway:
    component: apigateway # 这里引入的是相对路径，正式配置替换成你自己的component名称即可
    props:
      regionId: ${vars.region}
      customerDomain: ${vars.domain} # 客户自定义域名
      groupName: ${vars.gateway.groupName} #指定分组 这里你可以分开设置环境
      stageName: RELEASE
      apis:
        - apiName: barrageapi_get
          regionId: ${vars.region}
          requestConfig:
            requestPath: /api/*
            requestHttpMethod: GET
            requestMode: PASSTHROUGH
          serviceConfig:
            servicePath: /
            serviceProtocol: FunctionCompute
            functionComputeConfig:
              fcRegionId: ${vars.region}
              fcBaseUrl: ${http-control-center.output.url.system_url} # 或者直接使用 fcbaseurl
              onlyBusinessPath: true
              contentTypeCatagory: CLIENT
              path: /
            resultType: JSON
```
