### ISSUE TITLE
可否在build/deploy/local Invoke增加指定特定函数的功能?

### ISSUE THREAD

**Issue by shengwubin** [Serverless-Devs/Serverless-Devs#576]
```yaml
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: fcDeployApp       #  项目名称
access: "default"  #  秘钥别名

vars:
  service:
    name: fc-build-demo
    description: 'demo for fc-deploy component'
services:
  project1:
    component: devsapp/fc  # 组件名称
    props: #  组件的属性值
      region: cn-hangzhou
      service: ${vars.service}
      function:
        name: py-event-function-1
        description: this is a test
  project2:
    component: devsapp/fc  # 组件名称
    props: #  组件的属性值
      region: cn-hangzhou
      service: ${vars.service}
      function:
        name: py-event-function-2
        description: this is a test
```

假设使用下面的yaml进行s build，我会有py-event-function-1和py-event-function-2两个函数，但是当我进行deploy或者local Invoke的时候，我只能对所有的函数进行build,deploy,和local Invoke。

目前我的项目中，有8－10个函数，所以每次local invoke会依次调用全部函数，无法本地调试。
