### ISSUE TITLE
does this framework support deploying Next.js project?

### ISSUE THREAD

**Issue by newbaluku** [Serverless-Devs/Serverless-Devs#588]
does this framework support deploying Next.js project to Function compute?

**Comment by newbaluku** [comment]
i confirmed that the above issue is due to incompatibile Nodejs bundled in the custom image.

I manage to solve it by bundling Nodejs v12 myself during deploy but the downside is bloated code size.

I wonder if there is an option for us to specify the bundled Nodejs version in the custom image?

**Comment by heimanba** [comment]
You can use a custom layer to solve the version problem,

https://github.com/devsapp/layer-fc-plugin

The method of use is as follows

```
actions:
  pre-deploy:
    - plugin: layer-fc
      args:
        customRuntime: nodejs16
```

**Comment by newbaluku** [comment]
> @newbaluku
> 
> You can use a custom layer to solve the version problem,
> 
> https://github.com/devsapp/layer-fc-plugin
> 
> The method of use is as follows
> 
> ```
> actions:
>   pre-deploy:
>     - plugin: layer-fc
>       args:
>         customRuntime: nodejs16
> ```

Thanks for the tip! will try out :)

**Comment by newbaluku** [comment]
> @newbaluku
> 
> You can use a custom layer to solve the version problem,
> 
> https://github.com/devsapp/layer-fc-plugin
> 
> The method of use is as follows
> 
> ```
> actions:
>   pre-deploy:
>     - plugin: layer-fc
>       args:
>         customRuntime: nodejs16
> ```

Hi

may I know if I need to install the plugin somewhere?

I tried including the above pre-deploy action and get the following output from s:

[2022-10-18 16:55:14] [INFO] [S-CLI] - Action: undefined
[2022-10-18 16:55:14] [INFO] [S-CLI] - End the pre-action

couldn't find any installation instructions in the given github link.

**Comment by heimanba** [comment]
[start-express.zip](https://github.com/Serverless-Devs/Serverless-Devs/files/9829371/start-express.zip)
https://github.com/devsapp/layer-fc-plugin#%E8%87%AA%E5%AE%9A%E4%B9%89customRuntime%E7%89%88%E6%9C%AC

check this demo?

**Comment by newbaluku** [comment]
Hi @heimanba 

I have gone through the given url, but can't really figured out how to make it work for my sample project.

when i add the following:

actions:
  pre-deploy:
    - plugin: layer-fc
      args:
        customRuntime: nodejs14

or

actions:
  pre-deploy:
    - plugin: ${path(..)}
      args:
        customRuntime: nodejs14


I only get the following output during deploy:

[2022-10-23 17:11:22] [INFO] [S-CLI] - Start the pre-action
[2022-10-23 17:11:22] [INFO] [S-CLI] - Action: undefined

am I missing something?

I have uploaded my sample Nextjs project below:
https://github.com/newbaluku/nextjs-blog-ali-github

it will be great if you could help to point out what I need to add/change to include the desired Nodejs runtime.

Thanks.

**Comment by heimanba** [comment]
> Hi @heimanba
> 
> I have gone through the given url, but can't really figured out how to make it work for my sample project.
> 
> when i add the following:
> 
> actions: pre-deploy: - plugin: layer-fc args: customRuntime: nodejs14
> 
> or
> 
> actions: pre-deploy: - plugin: ${path(..)} args: customRuntime: nodejs14
> 
> I only get the following output during deploy:
> 
> [2022-10-23 17:11:22] [INFO] [S-CLI] - Start the pre-action [2022-10-23 17:11:22] [INFO] [S-CLI] - Action: undefined
> 
> am I missing something?
> 
> I have uploaded my sample Nextjs project below: https://github.com/newbaluku/nextjs-blog-ali-github
> 
> it will be great if you could help to point out what I need to add/change to include the desired Nodejs runtime.
> 
> Thanks.



it works

```
edition: 1.0.0
name: web-framework-app
access: "default"

vars:
  region: "ap-southeast-1"
  # region: "cn-hangzhou"
  service:
    name: "nextjs-blog-service"
    description: 'nextjs-blog service'

services:
  framework:
    component: fc
    actions:
      pre-deploy:
        - plugin: layer-fc
          args:
            customRuntime: nodejs16
        - run: npm run build
          path: ./code
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: nextjs-blog-app
        description: nextjs-blog App
        codeUri: './code'
        runtime: custom
        timeout: 60
        memorySize: 1024
        instanceConcurrency: 5
        # caPort: 9000
        # customRuntimeConfig:
        #   command:
        #     - npx
        #     - next
        #     - start
        #     - --port
        #     - '9000'
        environmentVariables:
          NODE_ENV: development
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: '/*'
```
![image](https://user-images.githubusercontent.com/5129967/197442947-b26c26f5-6aaf-4312-91e3-2ccfe8707588.png)
