### ISSUE TITLE
是否支持在同一台设备上同时运行两个 s 任务？

### ISSUE THREAD

**Issue by AielloChan** [Serverless-Devs/Serverless-Devs#637]
例如当前有两个函数 A、B，如果同时在 A 和 B 的函数目录下用命令行执行 s deploy XXXX，看起来两个部署行为是串行的？

当有大量函数需要频繁重新部署时（重新部署一个 service 下的所有函数），串行会显得比较耗时。

**Comment by heimanba** [comment]
有以下几种方式可以加速。
1. 如果只是部署代码，而不想部署service配置。可以使用`s deploy --type code`
![image](https://user-images.githubusercontent.com/5129967/221446548-210a4374-9d4f-4c1b-907e-7a5bcf60432f.png)

2. 如果有多个`services`例如
```
services:
  serviceA:
	 component: fc
	 props:
		...
  serviceB:
	component: fc
	props:
		...
```
假设需要部署`serviceB` 使用 `s  serviceB deploy`
