### ISSUE TITLE
魔法变量引用失败

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#7]
Yaml解析规则：
- 获取当前机器中的环境变量：${Env(环境变量)}，例如${Env(SecretId)}
- 获取外部文档的变量：${File(路径)}，例如${File(./path)}
- 获取全局变量：${Global.*}
- 获取其他项目的变量：${ProjectName.Properties.*}
- 获取Yaml中其他项目的结果变量：${ProjectName.Output.*}

**Comment by anycodes** [comment]
文件`demo.yaml`
```yaml
Global:
  Name: "myname"

MyFunctionDemo1:
  Component: test
  Provider: alibaba
  Properties:
    Name: ${Global.Name} # 预期结果 myname
    EnvPath: ${Env(PATH)} # 预期结果 环境变量的PATH
    FilePath: ${File(./test.yaml)} # 预期结果 abc: cde
    Key1: Value1

MyFunctionDemo2:
  Component: test
  Provider: alibaba
  Properties:
    Key1Output: ${MyFunctionDemo1.Output.Key1} # 预期结果 Value1
    Key1Input: ${MyFunctionDemo1.Properties.Key1} # 预期结果 Value1
    Path: ./src # 非${}结构的不做转译， 预期结果./src
    PathList: 
      - ./aaa # 非${}结构的不做转译， 预期结果./aaa
    
```

文件`test.yaml`：
```yaml
abc: cde
```
