### ISSUE TITLE
s config  add  有不落盘的实现方案

### ISSUE THREAD

**Issue by rsonghuster** [Serverless-Devs/Serverless-Devs#702]
s config add 落盘到 ~/.s/access.yaml 文件中， 虽然:

- 有加密处理， 但是 s 毕竟是开源的
- s config delete,  这个在 ci 流程中可能中途退出， 导致不一定能执行到

对于一些敏感账号的 ak 在 ci 机器上执行， 安全上的考量是必须的

## 现有方案

```
default_serverless_devs_access={\"AccountID\":\"temp_accountid\",\"AccessKeyID\":\"temp_accesskeyid\",\"AccessKeySecret\":\"temp_accesskeysecret\"} 
```

不太符合常规 cli 使用直觉

## 可行方案
1.   针对不同云产商， 直接使用不同的 env 识别，比如可以参考 tf

阿里云
```
export ALICLOUD_ACCESS_KEY=LTAIUrZCw3                
export ALICLOUD_SECRET_KEY=zfwwWAMWIAiooj14GQ2
```
aws
```
export AWS_ACCESS_KEY_ID=AKIAIOSxxxxxxx
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7Myyyyyyyy
```

2.  s config add 有不落盘的方案

s config add --AccessKeyID $ALICLOUD_ACCESS_KEY --AccessKeySecret $ALICLOUD_SECRET_KEY -f  --tmp  
这样也是符合用户直觉的，最后我们只需要对外透漏  s config add 这一个操作就好了

**Comment by penghuima** [comment]
目前考虑到账号的ak和sk比较敏感，不适宜出现在代码文件中，其次s config add不利于后续同学接管项目，因此采用了现有方案default_serverless_devs_access但是环境变量一般都是大写,但测试不通过，环境变量只能小写吗
```yaml
access: default_serverless_devs_access

vars: # 全局变量
  default_serverless_devs_access: ${env(DEFAULT_SERVERLESS_DEVS_ACCESS)}
```
