### ISSUE TITLE
模版中 each 语法不生效

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#735]
期望通过模版语法实现部署到多个region的需求
```
vars:
  regions:
    - cn-hangzhou
    - cn-zhangjiakou
    - cn-beijing
  service:
    name: midway-test
resources:
  {{each $vars.regions}}
  midway-test-{{$value}}:
    component: fc3
    props:
      region: cn-hangzhou
      functionName: midway-test-{{$value}}
  {{/each}}
```
