### ISSUE TITLE
部署edition:3的yaml文件时，报错`url: https://api.devsapp.cn/v3/packages/oss/release/latest is not found`

### ISSUE THREAD

**Issue by suyiiyii** [Serverless-Devs/Serverless-Devs#769]
**Describe the bug**
使用 ` s deploy `，部署`edition:3`的yaml文件时，报错`url: https://api.devsapp.cn/v3/packages/oss/release/latest is not found`

`oss`组件的文档给的示例是 `edition:1` 的，使用原先的完整的示例运行没有问题

但是`fc3`组件的示例是`edition:3`的，所以我尝试将oss模块迁移到新版的yaml文件中，就报了这个错误

Error Message:
```log
[2024-02-12 22:50:24][DEBUG] Error: url: https://api.devsapp.cn/v3/packages/oss/release/latest is not found
    at C:\Users\suyiiyii\AppData\Roaming\npm\node_modules\@serverless-devs\s\lib\index.js:323:10649
    at Generator.next (<anonymous>)
    at s (C:\Users\suyiiyii\AppData\Roaming\npm\node_modules\@serverless-devs\s\lib\index.js:323:7975)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```log
Env1: @serverless-devs/s: 3.0.1, win32-x64 node-v20.9.0    
Env2: FC Invoke Start RequestId: 014a0c6b-f3c2-4e16-af30-d225ceaa651cInfo: @serverless-cd/engine: 0.0.53, linux-x64, node-v14.19.2
```
尝试过在本地和阿里云fc平台上运行，均报此错误

```yaml
edition: 3.0.0 # 命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: serverless-dev-app # 项目名称
access: "default"

vars: # [全局变量，提供给各个项目使用]
  region: "cn-hangzhou"

resources: # 可以包括多个业务模块
  Function:
    component: fc3 # 组件名称
    props: # 组件的属性值
      region: ${vars.region}
      functionName: my-func
      runtime: python3.10
      code: server.py
      cpu: 0.25
      memorySize: 256
      diskSize: 512
      handler: index.handler
        
  front:
    component: oss
    props:
      bucket: auto
      codeUri: ./front
      region: ${vars.region}
      acl: public-read # 读写权限
      website:
        index: index.html
        error: 404.html
        subDirType: index
```

另外，关于yaml edition的变化，能不能在文档里面留一页旧版的规范，方便维护`edition:1`的yaml文件
谢谢
