### ISSUE TITLE
nodejs 子进程调用devs 获取不了环境变量

### ISSUE THREAD

**Issue by wss-git** [Serverless-Devs/Serverless-Devs#791]
如下所示，e.js 可以获得 环境变量。但是 s.yaml 无法转换

index.js
```
const { spawn } = require('child_process')
const fs = require('fs')

async function customSpawnSync(cmd, times) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, {
      shell: true,
      stdio: 'inherit',
      // encoding: 'utf-8',
      env: { ...process.env, times }
    });

    child.on('error', reject)
    // 子进程结束时输出
    child.on('close', resolve);
  })
}

(async () => {
  for (let times = 7; times <= 8; times++) {
    await customSpawnSync('node e', times)
  }
})()
```
e.js
```
console.log('process.env.times:: ', process.env.times)
```
s.yaml
```
edition: 1.0.0
name: component-test
access: default

vars:
  service:
    internetAccess: true
    name: lib1-base
  times: ${env('times')}

services:
  puppeteer:
    component: fc
    props:
      region: cn-qingdao
      service: ${vars.service}
      function:
        name: puppeteer-${vars.times}
        handler: index.handler
        timeout: 60
        runtime: nodejs14
        cpu: 0.05
        diskSize: 512
        instanceConcurrency: 1
        memorySize: 128
        codeUri: ./puppeteer
```
