### ISSUE TITLE
Support random string generation during template initialization

### ISSUE THREAD

**Issue by neurotoxinvx** [Serverless-Devs/Serverless-Devs#817]
**Is your feature request related to a problem? Please describe.**
在应用模版初始化时，需要为 `s.yaml` 中的部分资源随机生成 ID，例如：service-1fgxcsd
但是目前模版初始化阶段并不受到 component 控制，因此无法自主生成随机字符串并注入；

**Describe the solution you'd like**
在 `s.yaml` 中支持使用随机字符串变量，例如：

```yaml
vars:
  randomString: "{{ default-suffix }}"

resources:
    framework:
      component: fc3
    props:
      service-help: ${vars.randomString}
      service-help2: "id-{{ default-suffix }}"
        
```

**Describe alternatives you've considered**
尝试过在 publish.yaml 中声明新的属性，但是该属性会对用户暴露，用户可修改，使用体验不佳，例如：

```yaml
Parameters:
  type: object
  additionalProperties: false # 不允许增加其他属性
  required: # 必填项
    - randomString
  properties:
    randomString:
      title: 随机字符串
      type: string
      default: ${default-suffix}

```

**Additional context**
无
