### ISSUE TITLE
组件开发，执行npm run pub报“Error Message: 权限异常”

### ISSUE THREAD

**Issue by jinyang-dev** [Serverless-Devs/Serverless-Devs#822]
**Describe the bug**
1、按照如下链接init一个组件：
https://manual.serverless-devs.com/dev-guide/component/

2、修改publish.yaml为：

```yaml
Edition: 3.0.0
Type: Component
Name: j-serverless-devs-tool
Provider:
  - 阿里云 # 取值内容参考：https://api.devsapp.cn/v3/common/args.html
Version: 0.0.1
Description: 简短的描述/介绍
HomePage: 项目首页地址
Tags:
  - 部署函数
  - 部署组件
Category: 新手入门 # 取值内容参考：https://api.devsapp.cn/v3/common/args.html
Service:
  函数计算:
    Authorities: 
      - AliyunFCFullAccess
Commands:
  deploy: 部署函数
  invoke: 调用函数
Organization: 组织名称
Effective: Public
Parameters:
  type: object
  additionalProperties: false
  required: # 必填项
    - region
    - service
  properties:
    region: # 枚举类型
      default: cn-hangzhou
      title: 地域 # 名称
      enum: # 枚举
        - cn-beijing
        - cn-hangzhou
```

3、执行npm run login，再执行npm run pub，此时提示权限异常。

**Screenshots**
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/103874020/18adb48f-e004-410e-9266-c255a1f06103)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.4.1

**Additional context**
@serverless-devs/s: 3.0.7, s-home: /Users/xxx/.s, darwin-arm64, node-v20.12.2
