### ISSUE TITLE
Interaction in cicd environment, throwing exception

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#868]
**Describe the bug**
```log
  export PATH=./node_modules/.bin/:$PATH
  s config add --AccessKeyID $FC_ACCESS_KEY_ID --AccessKeySecret $FC_ACCESS_KEY_SECRET -f
  shell: /usr/bin/bash -e {0}
  env:
    FC_ACCESS_KEY_ID: ***
    FC_ACCESS_KEY_SECRET: ***
 
Error Message:
Interaction in cicd environment, throwing exception
```

在 GitHub Actions 中使用 s config add 命令时会提示上述错误

**Screenshots**

![image](https://github.com/user-attachments/assets/935c050a-6549-4f64-a9b7-432153e1d79d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4
 - Version 3.1.1

**Additional context**
[与 CI/CD 平台/工具集成](https://docs.serverless-devs.com/user-guide/cicd/) 文档中并未指出该如何绕过该问题

```yaml
name: Serverless Devs Project CI/CD

on:
  push:
    branches: [master]

jobs:
  serverless-devs-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm install -g @serverless-devs/s
      - run: s config add --AccessKeyID ${{secrets.AccessKeyID}} --AccessKeySecret ${{secrets.AccessKeySecret}} -a default -f
      - run: s deploy -y --use-local
```
