### ISSUE TITLE
s.yaml int字段不支持使用环境变量

### ISSUE THREAD

**Issue by pilaoda** [Serverless-Devs/Serverless-Devs#874]
**Describe the bug**
s.yaml
```
resources:
    service:
        component: fc3
        props:
            instanceConcurrency: ${env('INSTANCE_CONCURRENCY')}
```
.env
```
INSTANCE_CONCURRENCY=1
```
InvalidArgument: code: 400, json: cannot unmarshal string into struct field UpdateFunctionRequest.instanceConcurrency of type int32 request id: 1-66eaf5e0-15eee4ae-cc4cecccef90

**Desktop (please complete the following information):**
 - OS: windows11
 - Version 3.1.1

**Additional context**
希望用环境变量动态指定实例并发度
