### ISSUE TITLE
`s deploy` hang

### ISSUE THREAD

**Issue by glucn** [Serverless-Devs/Serverless-Devs#924]
**Describe the bug**
I'm running `s deploy` with Github actions to deploy changes to aliyun FC functions. It has been working fine in the past couple years, but recently (since about 2025-03-24), the deployments almost always hang for unknown reason. The FC function is updated, but the command does not pass.

I can reproduce this problem when running `s deploy` locally as well.

**Screenshots**

This is the screenshot of a timeout deployment. The deployment usually take about 3 min.
![Image](https://github.com/user-attachments/assets/8b58bb5d-5a43-4682-a13f-53df420f4d77)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.2 (this is the OS of Github action, my local testing used MacOS)
 - Version: `@serverless-devs/s: 3.1.9`

**Additional context**

Github action definition:
```
jobs:
  beta-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Initialize Serverless-Devs
        uses: Serverless-Devs/Serverless-Devs-Initialization-Action@v2
        with:
          AccountID: ${{ secrets.BETA_ALIYUN_ACCOUNT_ID }}
          AccessKeyID: ${{ secrets.BETA_ALIYUN_ACCESS_KEY_ID }}
          AccessKeySecret: ${{ secrets.BETA_ALIYUN_ACCESS_KEY_SECRET }}
      - name: Set secrets
         ...
      - name: Deploy application
        run: s deploy -y -t s.beta.yaml --debug
...
```

Please let me know if I can provide anything else to help the investigation. Thank you!

**Comment by zxypro1** [comment]
In recent versions, due to the compatibility issue of the Node version, there have been some changes in the code related to network requests. Maybe this is the cause of the problem. You can first lock the version of s to an earlier one, for example, 3.1.0. Also, please send the Node version, and we'll check where the problem lies. Btw, is this problem exist in your local MacOS?

**Comment by glucn** [comment]
> please send the Node version

I think it should be `20.19.0`, which I found from debug log when I add `--debug` flag:

```
[2025-03-31 04:07:52][DEBUG][ielts-mindlab-workflow-worker] input: {"cwd":"/home/runner/work/ielts-mindlab-service/ielts-mindlab-service","userAgent":"S3:3.1.9;Component:fc3@0.0.57;Env:github;Nodejs:v20.19.0;OS:linux-x64;","name":"ielts-mindlab-service","props":{"region":"cn-hangzhou","functionName":"ielts-mindlab-workflow-worker","runtime":"custom.debian10","description":"IELTS MindLab service","timeout":120,"memorySize":512,"cpu":0.5,"diskSize":512,"code":"./src","customRuntimeConfig":{"port":9000,"command":["python3","server.py"]},"vpcConfig":{"vpcId":"vpc-bp1abk2oypwlkbdbowcea","securityGroupId":"sg-bp1b296v0nekcqzh1y51","vSwitchIds":["vsw-bp1656c339dgeaxsgqfra"]},"ossMountConfig":{"mountPoints":[{"bucketName":"ielts-mindlab-***-beta","endpoint":"https://oss-cn-hangzhou-internal.aliyuncs.com/","mountDir":"/mnt/oss"}]},"environmentVariables":{"PYTHONPATH":"/code/python","PATH":"/code/python/bin:/var/fc/lang/python3.10/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin",
```

> Btw, is this problem exist in your local MacOS?

I can reproduce this issue locally not always, but sometimes (like, 50% chance)

**Comment by glucn** [comment]
> You can first lock the version of s to an earlier one, for example, 3.1.0

Do you mind to elaborate about how to do this? Is there such a option in `Serverless-Devs/Serverless-Devs-Initialization-Action@v2`

**Comment by zxypro1** [comment]
I checked that plugin and it does not support version specification. You can replace that plugin with these steps:

```yaml
 - name: Install Serverless-Devs 3.1.0
      run:  npm install -g @serverless-devs/s@3.1.0
      shell: bash
 - name: Configure Serverless-Devs
      run: s config add --AccountID ${{ secrets. BETA_ALIYUN_ACCOUNT_ID }} --AccessKeySecret ${{ secrets.BETA_ALIYUN_ACCESS_KEY_SECRET }} --AccessKeyID ${{ secrets.BETA_ALIYUN_ACCESS_KEY_ID }} -a default
```

**Comment by glucn** [comment]
To my surprise, using old version of `@serverless-devs/s` didn't mitigate this issue.
I tried `3.1.0` (the version you recommended) and `3.1.6` (the version persumbly right before the issue), neither of those worked.

There is something caught me attention when trying to run the deploy from local (MacOS), maybe not related, but still I'd like to mention it just in case it will be useful.

The following is the log at the end of the `s deploy` (with `--debug` flag) run on Github action:

```
✔ [ielts-mindlab-workflow-worker] completed (144.22s)
[2025-04-01 04:40:16][DEBUG][s_cli] getShownProps: undefined
[2025-04-01 04:40:16][DEBUG][s_cli] getShownProps: undefined
🚀  Result for [deploy] of [ielts-mindlab-service]
====================
ros-stack: 
  stackId:                        xxxxx
  status:                         UPDATE_COMPLETE
  VSwitchId:                      vsw-xxxx
  VpcId:                          vpc-xxxxx
  GenerateAnswerWorkflowTopicArn: acs:mns:cn-hangzhou:***:/topics/xxxx
  SecurityGroupId:                sg-xxxx
  MNSNotificationRoleArn:         acs:ram::***:role/mnsnotificationrole
  __component:                    ros
ielts-mindlab-api-service: 
  region:       cn-hangzhou
  functionName: xxxxx
  handler:      handler
  description:  xxxxx
  triggers: 
    - 
      triggerName: httpTrigger
      triggerType: http
ielts-mindlab-workflow-worker: 
  region:       cn-hangzhou
  functionName: xxxxx
  handler:      handler
  description:  xxxxx
  triggers: 
    - 
      triggerName: workflowTrigger
      triggerType: mns_topic
```

And when I run the same command locally, the output of the deploy result was with pretty much all the property of the FC function (I don't want to paste the full output because there are way too many secret that I need to redact....)

**Comment by zxypro1** [comment]
Could you also try 3.0.1, the stable version currently running in our workflow? If the problem still exists, it may not be a problem with Serverless Devs, but a problem with the components.

**Comment by glucn** [comment]
unfutunately, 3.0.1 still hangs...

Command is `s deploy -y -t s.beta.yaml --debug`

Output from Github action:

```
...
✔ [ielts-mindlab-workflow-worker] completed (51.91s)
🚀  Result for [deploy] of [ielts-mindlab-service]
====================
...
(omit the output of the stack, which shows many properties of FC functions)
...
A complete log of this run can be found in: /home/runner/.s/logs/0402034317

(it hangs here, no more output below)
```

As a comparison, I executed the same command locally, and the output was

```

✔ [ielts-mindlab-workflow-worker] completed (63.4s)

🚀  Result for [deploy] of [ielts-mindlab-service]
...
(omit the output of the stack)
...

A complete log of this run can be found in: /Users/garylu/.s/logs/0401204835

[2025-04-01 20:50:56][DEBUG][s_cli] Run traceid: 0401204835
[2025-04-01 20:50:56][DEBUG][s_cli] Process exitCode: 0

```

**Comment by zxypro1** [comment]
It seems unrelated to Serverless Devs but related to the fc3 component. I'll check what recent changes have been made to the component.

**Comment by zxypro1** [comment]
Could you add `export core_load_serverless_devs_component=fc3@0.0.40` before `s deploy` and run again?

**Comment by glucn** [comment]
It hangs at the same spot

```
...
A complete log of this run can be found in: /home/runner/.s/logs/0406052759
```

Btw, this is the Github action definition I was using:

```
      - name: Print @serverless-devs/s version
        run: s --version
      - name: Test
        run: export core_load_serverless_devs_component=fc3@0.0.40
      - name: Deploy application
        run: s deploy -y -t s.beta.yaml --debug
```

**Comment by zxypro1** [comment]
Asked an employee at AliCloud Functional Computing about this, and it could be caused by a network issue with the FC APIs. Can you try locally to call FC's OpenAPI? The URL is here: [Alibaba Cloud OpenAPI](https://api.alibabacloud.com/)

**Comment by zxypro1** [comment]
> It hangs at the same spot
> 
> ```
> ...
> A complete log of this run can be found in: /home/runner/.s/logs/0406052759
> ```
> 
> Btw, this is the Github action definition I was using:
> 
> ```
>       - name: Print @serverless-devs/s version
>         run: s --version
>       - name: Test
>         run: export core_load_serverless_devs_component=fc3@0.0.40
>       - name: Deploy application
>         run: s deploy -y -t s.beta.yaml --debug
> ```

Asked an employee at AliCloud Functional Computing about this, and it could be caused by a network issue with the FC APIs. Can you try locally to call FC's OpenAPI? The URL is here: [Alibaba Cloud OpenAPI](https://api.alibabacloud.com/)

**Comment by glucn** [comment]
I tested both locally and on Github action, using aliyun-cli. There is no problem accessing the API.

```
Run curl -O -fsSL https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz; tar zxf aliyun-cli-linux-latest-amd64.tgz; ./aliyun configure set --profile default --mode AK --access-key-id *** --access-key-secret *** --region cn-hangzhou; ./aliyun fc GET /2023-03-30/functions --header "Content-Type=application/json;"
{
	"functions": [
                 ...
		(omit the output here)
                 ...
	]
}
```

**Comment by OOWhereAreYou** [comment]
``` js

import archiver from 'archiver';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import OpenApi, * as $OpenApi from '@alicloud/openapi-client';
import * as $Util from '@alicloud/tea-util';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ALIBABA_CLOUD_ACCESS_KEY_ID = "...";
const ALIBABA_CLOUD_ACCESS_KEY_SECRET = "...";

export default class Client {
  /**
   * @remarks
   * 使用AK&SK初始化账号Client
   * @returns Client
   *
   * @throws Exception
   */
  static createClient() {
    let config = new $OpenApi.Config({
      accessKeyId: ALIBABA_CLOUD_ACCESS_KEY_ID,
      accessKeySecret: ALIBABA_CLOUD_ACCESS_KEY_SECRET,
    });
    config.endpoint = `1461309719527070.cn-beijing.fc.aliyuncs.com`;
    const client = new OpenApi.default(config);
    return client;
  }

  /**
   * @remarks
   * API 相关
   *
   * @param path - string Path parameters
   * @returns OpenApi.Params
   */
  static createApiInfo(functionName) {
    let params = new $OpenApi.Params({
      // 接口名称
      action: "UpdateFunction",
      // 接口版本
      version: "2023-03-30",
      // 接口协议
      protocol: "HTTPS",
      // 接口 HTTP 方法
      method: "PUT",
      authType: "AK",
      style: "FC",
      // 接口 PATH
      pathname: `/2023-03-30/functions/${functionName}`,
      // 接口请求体内容格式
      reqBodyType: "json",
      // 接口响应体内容格式
      bodyType: "json",
    });
    return params;
  }
}

async function zipFunctionCode(functionCode) {
  const zipPath = path.join(__dirname, "../function.zip");
  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver("zip", {
      zlib: { level: 9 }, // 设置压缩级别
    });

    output.on("close", () => {
      resolve(zipPath);
    });

    archive.on("error", function (err) {
      reject(err);
    });

    archive.pipe(output);
    archive.directory(functionCode, false);
    archive.finalize();
  });
}

async function main() {
  // 检查环境变量
  if (!ALIBABA_CLOUD_ACCESS_KEY_ID || !ALIBABA_CLOUD_ACCESS_KEY_SECRET) {
    console.error("请设置 ALIBABA_CLOUD_ACCESS_KEY_ID 和 ALIBABA_CLOUD_ACCESS_KEY_SECRET 环境变量");
    process.exit(1);
  }
  let client = Client.createClient();

  const functionName = "...";
  const functionCode = path.join(__dirname, "../.next/standalone");
  let params = Client.createApiInfo(functionName);

  // 压缩代码
  const zipPath = await zipFunctionCode(functionCode);

  // 读取压缩文件
  const zipFile = fs.readFileSync(zipPath);

  // runtime options
  let runtime = new $Util.RuntimeOptions({
    connectTimeout: 60000, // 连接超时时间设置为30秒
    readTimeout: 60000, // 读取超时时间设置为30秒
  });
  let request = new $OpenApi.OpenApiRequest({
    body: {
      code: {
        zipFile: zipFile.toString("base64"),
      },
     // 其他配置
    },
  });

  await client.callApi(params, request, runtime);
  fs.unlinkSync(zipPath);
}

main().then(() => {
  console.log("部署成功");
  process.exit(0);
});
```
我写了一个脚本函数可以

**Comment by zxypro1** [comment]
> I tested both locally and on Github action, using aliyun-cli. There is no problem accessing the API.
> 
> ```
> Run curl -O -fsSL https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz; tar zxf aliyun-cli-linux-latest-amd64.tgz; ./aliyun configure set --profile default --mode AK --access-key-id *** --access-key-secret *** --region cn-hangzhou; ./aliyun fc GET /2023-03-30/functions --header "Content-Type=application/json;"
> {
> 	"functions": [
>                  ...
> 		(omit the output here)
>                  ...
> 	]
> }
> ```
Please paste your s.yaml. It seems that I have to reproduce this problem to fix it. Before this issue is fixed, consider using OpenAPI for deployment.

**Comment by tsezed** [comment]
any workaround solution for this issue? pipeline keep hanging for hours, but the deployment is successful

**Comment by glucn** [comment]
> Please paste your s.yaml. It seems that I have to reproduce this problem to fix it. Before this issue is fixed, consider using OpenAPI for deployment.


```
edition: 3.0.0
name: ielts-mindlab-service
access: default

vars:
  region: cn-hangzhou
  stage: _PLACEHOLDER_
  generate-answer-workflow-topic-name: ielts-mindlab-generate-answer
  api-handler-function-name: _PLACEHOLDER_
  workflow-worker-function-name: _PLACEHOLDER_
  mysql-host: _PLACEHOLDER_
  mns-endpoint: _PLACEHOLDER_
  bucket-name: _PLACEHOLDER_
  wechat-pay-callback-url: _PLACEHOLDER_

resources:
  ielts-mindlab-api-service:
    component: fc3 
    actions:       
      pre-deploy:
        - component: fc3 build
    props:
      region: ${vars.region}
      functionName: ${vars.api-handler-function-name}
      runtime: custom.debian10
      description: 'Service'
      timeout: 120
      memorySize: 512
      cpu: 0.5
      diskSize: 512
      code: ./src
      customRuntimeConfig:
        port: 9000
        command:
          - python3
          - server.py
      vpcConfig:
        vpcId: ${resources.ros-stack.output.VpcId}
        securityGroupId: ${resources.ros-stack.output.SecurityGroupId}
        vSwitchIds:
          - ${resources.ros-stack.output.VSwitchId}
      ossMountConfig:
        mountPoints:
          - bucketName: ${vars.bucket-name}
            endpoint: https://oss-cn-hangzhou-internal.aliyuncs.com # TODO
            mountDir: /mnt/oss # TODO
      environmentVariables:
        PYTHONPATH: /code/python
        PATH: /code/python/bin:/var/fc/lang/python3.10/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
        STAGE: ${vars.stage}
        ADMINS: _ADMINS_PLACEHOLDER_
        MYSQL_HOST: ${vars.mysql-host}
        MYSQL_PORT: "3306"
        MYSQL_USER: _MYSQL_USER_PLACEHOLDER_
        MYSQL_PASSWORD: _MYSQL_PASSWORD_PLACEHOLDER_
        MYSQL_DBNAME: ielts_mindlab
        WORKFLOW_MNS_ENDPOINT: ${vars.mns-endpoint}
        WORKFLOW_QUEUE_NAME: ${vars.generate-answer-workflow-topic-name}
        WEIXIN_APP_ID: _WEIXIN_APP_ID_PLACEHOLDER_
        WEIXIN_APP_SECRET: _WEIXIN_APP_SECRET_PLACEHOLDER_
        DASHSCOPE_API_KEY: _DASHSCOPE_API_KEY_PLACEHOLDER_
        BUCKET_NAME: ${vars.bucket-name}
        WECHAT_PAY_API_KEY: _WECHAT_PAY_API_KEY_PLACEHOLDER_
        WECHAT_PAY_CALLBACK_URL: ${vars.wechat-pay-callback-url}
      triggers:
        - triggerName: httpTrigger
          triggerType: http
          description: 'IELTS MindLab service HTTP trigger'
          qualifier: LATEST
          triggerConfig:
            authType: anonymous # TODO: Add auth
            disableURLInternet: false
            methods:
              - GET
              - POST
              - OPTIONS
              - HEAD

  ielts-mindlab-workflow-worker:
    component: fc3 
    actions:       
      pre-deploy:
        - component: fc3 build
    props:
      region: ${vars.region}
      functionName: ${vars.workflow-worker-function-name}
      runtime: custom.debian10
      description: 'Workflow worker'
      timeout: 120
      memorySize: 512
      cpu: 0.5
      diskSize: 512
      code: ./src
      customRuntimeConfig:
        port: 9000
        command:
          - python3
          - server.py
      vpcConfig:
        vpcId: ${resources.ros-stack.output.VpcId}
        securityGroupId: ${resources.ros-stack.output.SecurityGroupId}
        vSwitchIds:
          - ${resources.ros-stack.output.VSwitchId}
      ossMountConfig:
        mountPoints:
          - bucketName: ${vars.bucket-name}
            endpoint: https://oss-cn-hangzhou-internal.aliyuncs.com # TODO
            mountDir: /mnt/oss # TODO
      environmentVariables:
        PYTHONPATH: /code/python
        PATH: /code/python/bin:/var/fc/lang/python3.10/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
        STAGE: ${vars.stage}
        ADMINS: _ADMINS_PLACEHOLDER_
        MYSQL_HOST: ${vars.mysql-host}
        MYSQL_PORT: "3306"
        MYSQL_USER: _MYSQL_USER_PLACEHOLDER_
        MYSQL_PASSWORD: _MYSQL_PASSWORD_PLACEHOLDER_
        MYSQL_DBNAME: ielts_mindlab
        WORKFLOW_MNS_ENDPOINT: ${vars.mns-endpoint}
        WORKFLOW_QUEUE_NAME: ${vars.generate-answer-workflow-topic-name}
        WEIXIN_APP_ID: _WEIXIN_APP_ID_PLACEHOLDER_
        WEIXIN_APP_SECRET: _WEIXIN_APP_SECRET_PLACEHOLDER_
        DASHSCOPE_API_KEY: _DASHSCOPE_API_KEY_PLACEHOLDER_
        BUCKET_NAME: ${vars.bucket-name}
        WECHAT_PAY_API_KEY: _WECHAT_PAY_API_KEY_PLACEHOLDER_
        WECHAT_PAY_CALLBACK_URL: ${vars.wechat-pay-callback-url}
      triggers:
        - triggerName: workflowTrigger
          triggerType: mns_topic
          description: 'IELTS MindLab workflow trigger'
          qualifier: LATEST
          sourceArn: ${resources.ros-stack.output.GenerateAnswerWorkflowTopicArn}
          # This role was created from console. TODO: Setup this role automatically
          role: ${resources.ros-stack.output.MNSNotificationRoleArn}
          triggerConfig:
            notifyContentFormat: JSON
            notifyStrategy: EXPONENTIAL_DECAY_RETRY

  ros-stack:
    component: ros
    props:
      region: ${vars.region}
      name: ielts-mindlab-ros-stack
      template: ./ros_template.yaml
      parameters:
        GenerateAnswerWorkflowTopicName: ${vars.generate-answer-workflow-topic-name}
        BucketName: ${vars.bucket-name}

```

There are also `s.beta.yaml` and `s.prod.yaml`

```
extend: s.yaml

vars:
  stage: beta
  api-handler-function-name: ielts-mindlab-c39b6e33
  workflow-worker-function-name: ielts-mindlab-workflow-worker
  mysql-host: xxxxxxxxxxx
  mns-endpoint: xxxxxxxxxxx
  bucket-name: xxxxxxxxxxx
  wechat-pay-callback-url: xxxxxxxxxxx


resources:
  ielts-mindlab-api-service:
    props:
      role: xxxxxxxxxxx
      logConfig: # Created by "logConfig: auto"
        enableInstanceMetrics: true
        enableRequestMetrics: true
        logBeginRule: DefaultRegex
        project: xxxxxxxxxxx
        logstore: function-logstore

  ielts-mindlab-workflow-worker:
    props:
      logConfig: # Created by "logConfig: auto"
        enableInstanceMetrics: true
        enableRequestMetrics: true
        logBeginRule: DefaultRegex
        project: xxxxxxxxxxx
        logstore: default-logs
```

**Comment by mcitem** [comment]
> > 我使用 aliyun-cli 在本地和 Github作上进行了测试。访问 API 没有问题。
> > ```
> > Run curl -O -fsSL https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz; tar zxf aliyun-cli-linux-latest-amd64.tgz; ./aliyun configure set --profile default --mode AK --access-key-id *** --access-key-secret *** --region cn-hangzhou; ./aliyun fc GET /2023-03-30/functions --header "Content-Type=application/json;"
> > {
> > 	"functions": [
> >                  ...
> > 		(omit the output here)
> >                  ...
> > 	]
> > }
> > ```
> 
> 请粘贴您的 s.yaml。看来我必须重现这个问题才能解决它。在解决此问题之前，请考虑使用 OpenAPI 进行部署。

Encountering the same problem, in Alibaba Cloud Function Compute fc

```
edition: 3.0.0
name: fc3-example
access: default
resources:
  fcDemo:
    component: fc3
    props:
      region: cn-shenzhen
      handler: index.handler
      disableOndemand: false
      description: ""
      timeout: 60
      diskSize: 512
      internetAccess: true
      customRuntimeConfig:
        port: 9000
        command:
          - ./api
      functionName: func-func1
      runtime: custom
      cpu: 0.5
      instanceConcurrency: 20
      memorySize: 512
      code: ./
```
